"""Add new fields to AdoptionForm

Revision ID: 19840da7d9c7
Revises: 969f78a5be48
Create Date: 2025-02-11 15:17:44.844521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19840da7d9c7'
down_revision = '969f78a5be48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('residence_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('has_other_pets', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('pet_alone_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pet_sleeping_place', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_previous_adoption', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('reason_for_adoption', sa.Text(), nullable=False))
        batch_op.drop_column('is_renter')
        batch_op.drop_column('why_adopt')
        batch_op.drop_column('reference_contact')
        batch_op.drop_column('has_pets')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('pet_experience')
        batch_op.drop_column('has_children')
        batch_op.drop_column('house_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('has_children', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('pet_experience', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('employment_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('has_pets', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('reference_contact', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('why_adopt', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('is_renter', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('reason_for_adoption')
        batch_op.drop_column('has_previous_adoption')
        batch_op.drop_column('pet_sleeping_place')
        batch_op.drop_column('pet_alone_hours')
        batch_op.drop_column('has_other_pets')
        batch_op.drop_column('residence_type')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
