"""empty message

Revision ID: 319a65b94683
Revises: ff3c2b62a116
Create Date: 2025-02-11 21:32:26.753152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319a65b94683'
down_revision = 'ff3c2b62a116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
