"""empty message

Revision ID: e8b4a3e1eb2b
Revises: 19840da7d9c7
Create Date: 2025-02-11 19:15:04.226017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b4a3e1eb2b'
down_revision = '19840da7d9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_forms') as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_forms', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
